name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.0.0
  cloud_firestore: ^0.13.0+1
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  modal_progress_hud: ^0.1.3
  rflutter_alert: ^1.0.3
  shared_preferences: ^0.5.6+1
  http: ^0.12.0+4
  firebase_storage: ^3.1.1
  image_picker: ^0.6.3+1
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  geolocator: ^5.2.1
  redux_persist_flutter: ^0.8.2
  google_maps_flutter: ^0.5.23+1
  json_serializable: ^2.0.2
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
